//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accesos()
        {
            this.Notificaciones = new HashSet<Notificaciones>();
        }
    
        public int id { get; set; }
        public int idEstudiante { get; set; }
        public int idPuntoAcceso { get; set; }
        public System.DateTime fechaHora { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual PuntosAcceso PuntosAcceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
    }
}
