//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC3()
        {
            this.DC3Documento = new HashSet<DC3Documento>();
            this.DC3Firma = new HashSet<DC3Firma>();
        }
    
        public int Id { get; set; }
        public string Folio { get; set; }
        public int TrabajadorId { get; set; }
        public int EmpresaId { get; set; }
        public int CursoId { get; set; }
        public int CapacitadorId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int CertificadorId { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Capacitador Capacitador { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC3Documento> DC3Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC3Firma> DC3Firma { get; set; }
    }
}
