//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC3Firma
    {
        public int Id { get; set; }
        public int DC3Id { get; set; }
        public string TipoFirma { get; set; }
        public string NombreFirmante { get; set; }
        public string RutaArchivo { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
    
        public virtual DC3 DC3 { get; set; }
    }
}
