//------------------------------------------------------------------------------
// <auto-generated>
//     Entidad sincronizada con dbo.Documento mediante HelpDesk.edmx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;

    public partial class Documento
    {
        public int Id { get; set; }
        public Guid SyncGuid { get; set; }
        public string Folio { get; set; }
        public string TipoDocumento { get; set; }
        public string Estado { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<DateTime> FechaDocumento { get; set; }
        public string ContenidoJson { get; set; }
        public bool Activo { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    }
}
