//------------------------------------------------------------------------------
// <auto-generated>
//     Entidad sincronizada con dbo.DocumentoSeccion mediante HelpDesk.edmx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;

    public partial class DocumentoSeccion
    {
        public int Id { get; set; }
        public int DocumentoId { get; set; }
        public Guid SyncGuid { get; set; }
        public int Orden { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public bool Activo { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    }
}
