//------------------------------------------------------------------------------
// <auto-generated>
//     Entidad sincronizada con dbo.DocumentoFirma mediante HelpDesk.edmx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;

    public partial class DocumentoFirma
    {
        public int Id { get; set; }
        public int DocumentoId { get; set; }
        public Guid SyncGuid { get; set; }
        public int Orden { get; set; }
        public string TipoFirma { get; set; }
        public string NombreFirmante { get; set; }
        public string CargoFirmante { get; set; }
        public Nullable<DateTime> FechaFirma { get; set; }
        public string RutaArchivo { get; set; }
        public byte[] Firma { get; set; }
        public bool Activo { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    }
}
