//------------------------------------------------------------------------------
// <auto-generated>
//     Entidad sincronizada con dbo.DocumentoConcepto mediante HelpDesk.edmx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;

    public partial class DocumentoConcepto
    {
        public int Id { get; set; }
        public int DocumentoId { get; set; }
        public Guid SyncGuid { get; set; }
        public int Orden { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public string Unidad { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Importe { get; set; }
        public bool Activo { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    }
}
