//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int Id { get; set; }
        public System.Guid SyncGuid { get; set; }
        public string Folio { get; set; }
        public string TipoDocumento { get; set; }
        public string Estado { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string Notas { get; set; }
        public string ClienteNombre { get; set; }
        public string ResponsableNombre { get; set; }
        public string ResponsablePuesto { get; set; }
        public string LugarEmision { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public string ContenidoJson { get; set; }
        public decimal SubTotal { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public string RutaUltimoPdf { get; set; }
        public Nullable<System.DateTime> PdfGeneratedAt { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    }
}
