//------------------------------------------------------------------------------
// <auto-generated>
//     Entidad sincronizada con dbo.DocumentoSeccionImagen mediante HelpDesk.edmx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;

    public partial class DocumentoSeccionImagen
    {
        public int Id { get; set; }
        public int DocumentoSeccionId { get; set; }
        public Guid SyncGuid { get; set; }
        public int Orden { get; set; }
        public string NombreArchivo { get; set; }
        public string MimeType { get; set; }
        public string RutaArchivo { get; set; }
        public byte[] Imagen { get; set; }
        public string TextoAlternativo { get; set; }
        public bool Activo { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
    }
}
