//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudiantesXTutor
    {
        public int id { get; set; }
        public int idEstudiante { get; set; }
        public int idTutor { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Tutores Tutores { get; set; }
    }
}
