//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int id { get; set; }
        public int idAcceso { get; set; }
        public int idPadreTutor { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string texto { get; set; }
        public string estado { get; set; }
    
        public virtual Accesos Accesos { get; set; }
        public virtual Tutores Tutores { get; set; }
    }
}
