//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntosAcceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuntosAcceso()
        {
            this.Accesos = new HashSet<Accesos>();
        }
    
        public int id { get; set; }
        public int idPlantel { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public Nullable<System.DateTime> FechaHoraInstalacion { get; set; }
        public Nullable<bool> estado { get; set; }
        public string apiServer { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesos> Accesos { get; set; }
        public virtual Planteles Planteles { get; set; }
    }
}
