//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.DC3 = new HashSet<DC3>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string CURP { get; set; }
        public string Puesto { get; set; }
        public Nullable<int> OcupacionId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC3> DC3 { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
    }
}
