//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr_profile
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updateAt { get; set; }
        public Nullable<System.DateTime> fecha_nacimeinto { get; set; }
        public string Cel { get; set; }
        public string Género { get; set; }
        public string Estado { get; set; }
        public byte[] Foto_usuario { get; set; }
        public int id_User { get; set; }
        public Nullable<int> NumeroCertificadosDisponibles { get; set; }
        public Nullable<int> NumeroCertificadosUsados { get; set; }
        public Nullable<System.DateTime> FechaVigenciaPaquete { get; set; }
    
        public virtual User User { get; set; }
    }
}
